INSERT INTO artistas (nome)
VALUES
('Troye Sivan'), ('Taylor Swift');

INSERT INTO albuns (titulo, artistaID, genero, anoLancamento) VALUES
('Something to Give Each Other', 1, 'Pop', 2023),
('folklore (deluxe version)', 2, 'Alternativo', 2020),
('Blue Neighbourhood (Deluxe)', 1, 'Pop', 2015),
('1989 Deluxe Edition', 2, 'Pop', 2014);


INSERT INTO musicas (titulo, duracao, artistaID, albumID) VALUES
('Rush', INTERVAL '2 minutes 36 seconds', 1, 1),
('What''s The Time Where You Are?', INTERVAL '3 minutes 24 seconds', 1, 1),
('One Of Your Girls', INTERVAL '3 minutes 1 seconds', 1, 1),
('In My Room (feat. Guitarricadelafuente)', INTERVAL '3 minutes 13 seconds', 1, 1),
('Still Got It', INTERVAL '3 minutes 29 seconds', 1, 1),
('Can''t Go Back, Baby', INTERVAL '3 minutes 22 seconds', 1, 1),
('Got Me Started', INTERVAL '3 minutes 18 seconds', 1, 1),
('Silly', INTERVAL '3 minutes 39 seconds', 1, 1),
('Honey', INTERVAL '3 minutes 27 seconds', 1, 1),
('How to Stay with You', INTERVAL '3 minutes 16 seconds', 1, 1),

('Cardigan', INTERVAL '3 minutes 59 seconds', 2, 2),
('The 1', INTERVAL '3 minutes 30 seconds', 2, 2),
('The Last Great American Dynasty', INTERVAL '3 minutes 51 seconds', 2, 2),
('Exile', INTERVAL '4 minutes 45 seconds', 2, 2),
('My Tears Ricochet', INTERVAL '4 minutes 15 seconds', 2, 2),
('Mirrorball', INTERVAL '3 minutes 29 seconds', 2, 2),
('Seven', INTERVAL '3 minutes 28 seconds', 2, 2),
('August', INTERVAL '4 minutes 21 seconds', 2, 2),
('This Is Me Trying', INTERVAL '3 minutes 15 seconds', 2, 2),
('Illicit Affairs', INTERVAL '3 minutes 11 seconds', 2, 2),
('Invisible String', INTERVAL '4 minutes 12 seconds', 2, 2),
('Mad Woman', INTERVAL '3 minutes 57 seconds', 2, 2),
('Epiphany', INTERVAL '4 minutes 49 seconds', 2, 2),
('Betty', INTERVAL '4 minutes 54 seconds', 2, 2),
('Peace', INTERVAL '3 minutes 54 seconds', 2, 2),
('Hoax', INTERVAL '3 minutes 40 seconds', 2, 2),
('The Lakes', INTERVAL '3 minutes 32 seconds', 2, 2),

('Wild', INTERVAL '3 minutes 47 seconds', 1, 3),
('Bite', INTERVAL '3 minutes 6 seconds', 1, 3),
('Fools', INTERVAL '3 minutes 40 seconds', 1, 3),
('Ease', INTERVAL '3 minutes 34 seconds', 1, 3),
('The Quiet', INTERVAL '3 minutes 46 seconds', 1, 3),
('DKLA', INTERVAL '4 minutes 14 seconds', 1, 3),
('Talk Me Down', INTERVAL '3 minutes 57 seconds', 1, 3),
('Cool', INTERVAL '3 minutes 19 seconds', 1, 3),
('Heaven', INTERVAL '4 minutes 21 seconds', 1, 3),
('Youth', INTERVAL '3 minutes 5 seconds', 1, 3),
('Lost Boy', INTERVAL '3 minutes 42 seconds', 1, 3),
('for him.', INTERVAL '3 minutes 29 seconds', 1, 3),
('Suburbia', INTERVAL '3 minutes 54 seconds', 1, 3),
('Too Good', INTERVAL '3 minutes 45 seconds', 1, 3),
('Blue', INTERVAL '3 minutes 30 seconds', 1, 3),
('Wild', INTERVAL '4 minutes 18 seconds', 1, 3),

('Welcome to New York', INTERVAL '3 minutes 32 seconds', 2, 4),
('Blank Space', INTERVAL '3 minutes 51 seconds', 2, 4),
('Style', INTERVAL '3 minutes 51 seconds', 2, 4),
('Out of the Woods', INTERVAL '3 minutes 55 seconds', 2, 4),
('All You Had to Do Was Stay', INTERVAL '3 minutes 13 seconds', 2, 4),
('Shake It Off', INTERVAL '3 minutes 39 seconds', 2, 4),
('I Wish You Would', INTERVAL '3 minutes 27 seconds', 2, 4),
('Bad Blood', INTERVAL '3 minutes 31 seconds', 2, 4),
('Wildest Dreams', INTERVAL '3 minutes 40 seconds', 2, 4),
('How You Get the Girl', INTERVAL '4 minutes 7 seconds', 2, 4),
('This Love', INTERVAL '4 minutes 10 seconds', 2, 4),
('I Know Places', INTERVAL '3 minutes 15 seconds', 2, 4),
('Clean', INTERVAL '4 minutes 31 seconds', 2, 4),
('Wonderland', INTERVAL '4 minutes 5 seconds', 2, 4),
('You Are in Love', INTERVAL '4 minutes 27 seconds', 2, 4),
('New Romantics', INTERVAL '3 minutes 50 seconds', 2, 4);
